sudo: required

language: php

services:
  - docker

before_script:
  - docker build -t swoft/framework .
  - docker run swoft/framework /bin/sh -c "cd /var/www/swoft; /var/www/swoft/vendor/bin/phpunit -c /var/www/swoft/phpunit.xml"

script: composer test
