sudo: required

language: php

services:
  - docker

before_script:
  - docker build -t swoft/framework .
  - docker run swoft/framework /bin/sh -c "cd /var/www/swoft; composer test"

script: composer test
