language: php

php:
  - 7.0
  - 7.1

before_script:
  - wget https://github.com/redis/hiredis/archive/v0.13.3.tar.gz -O hiredis.tar.gz && mkdir -p hiredis && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 && cd hiredis && sudo make -j$(nproc) && sudo make install && sudo ldconfig
  - pecl install -f swoole-2.0.9
  - composer install --dev

script: composer test
